--- !ditz.rubyforge.org,2008-03-06/project 
name: cinit
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: cinit
- !ditz.rubyforge.org,2008-03-06/component 
  name: core
- !ditz.rubyforge.org,2008-03-06/component 
  name: user interface
- !ditz.rubyforge.org,2008-03-06/component 
  name: portability
releases: []

