#!/bin/sh
# Nico Schottelius (nico-cinit /at/ schottelius.org)
# 2007-05-21
# Behave as being shutdown from Linux' sysvinit

# parse options, display usage

# all the functions

usage()
{

cat << cinit_usage

*** cinit linux-sysvinit shutdown wrapper ***

Usage   shutdown [-akrhHPfnc] [-t secs] time [warning message]
        -a:      use /etc/shutdown.allow
        -k:      don't really shutdown, only warn.
        -r:      reboot after shutdown.
        -h:      halt after shutdown.
        -P:      halt action is to turn off power.
        -H:      halt action is to just halt.
        -f:      do a 'fast' reboot (skip fsck).
        -F:      Force fsck on reboot.
        -n:      do not go through "init" but go down real fast.
        -c:      cancel a running shutdown.
        -t secs: delay between warning and kill signal.
        ** the "time" argument is mandatory! (try "now") **

You can also call "cmd" directly instead of using this wrapper.

cinit_usage

}

# the main part
usage
