#!/bin/sh
# Nico Schottelius
# 2007-05-20, 0110 CEST
# cconfig: create makefile from conf/ directory
# currently: all files
# later: only built-defines
# 


CONFS=$($(dirname $0)/cinit.get-confdir)/../conf/*

echo "#"
echo "# Warning: Autogenerated by $0, do not edit. "
echo "#"
for conf in ${CONFS}; do
   NAME="$(basename $conf | tr a-z A-Z)"
   value=$(head -n 1 $conf)

   echo "${NAME}=${value}"
done
