#
# Makefile for cinit tests
#
# Nico Schottelius
#
# Don't edit Makefiles, use conf/* for configuration.
#

TEST_BUILD_ARGV=test/test_build_argv.o core/build_argv.o

PROGS=test_build_argv test_build_argv_link

tests: $(PROGS)

test_build_argv: test/test_build_argv.o core/build_argv.o
test_build_argv_link: test/test_build_argv+link.o core/build_argv.o

test_gen_svc_tree: test/test_gen_svc_tree.o svc/list_display_all.o \
							svc/list_display_all.o \
							svc/list_display_all.o \
							svc/list_display_all.o \
							svc/list_display_all.o \
							svc/gen_svc_tree.o 		\
							generic/mini_printf.o \
							svc/list_display_all.o
