.TH cinit 8 2005-08-21
.SH NAME
cinit - fast executing, small and simple init with profile-support
.SH SYNOPSIS
/sbin/cinit cprofile:<theprofile>
.SH DESCRIPTION
cinit is a fast executing, small and simple init with support for profiles. It minds dependencies (hard and soft, 'needs' and 'wants') and executes processes in parallel. And it has a simple configuration, which makes many shell-scripts unecessary (but you still could use them if you really want), which leads to better performance and less memory using.
.SH AVAILABILITY
cinit is currently Linux-specific.
.SH EXAMPLES
See http://linux.schottelius.org/cinit/#config
.SH SEE ALSO
http://linux.schottelius.org/cinit/
.SH AUTHOR
Nico Schottelius <nico-linux-cinit // schottelius.org>
.SH FILES
.IP "/sbin/cinit - the init system" 
.IP "/sbin/cservice - control cinit" 
.IP "/sbin/cinit.reboot (/sbin/reboot if non-existent before)" 
.IP "/sbin/cinit.shutdown (/sbin/shutdown if non-existent before)" 
.IP "/etc/cinit - configuration directory" 
