.TH cservice 8 2005-08-21
.SH NAME
cservice - fast executing, small and simple init with profile-support
.SH SYNOPSIS
/sbin/cservice [-eaphru] [thilo]
.SH DESCRIPTION
cservice controls cinit. Please use cservice -h for help.
.SH SEE ALSO
http://linux.schottelius.org/cinit/
.SH AUTHOR
Nico Schottelius <nico-linux-cinit // schottelius.org>
